In [1]:
#Numpy Arrays

import numpy as np

In [2]:
a = np.array([1, 2, 3])

print(a)

[1 2 3]


In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
# Minimum dimensions

a = np.array([1, 2, 3, 5], ndmin = 2)
print(a)

[[1 2 3 5]]


In [7]:
# dtype parameter

a = np.array([1, 2, 3], dtype = complex)

print(a)

[1.+0.j 2.+0.j 3.+0.j]


## Numpy Data Types

In [8]:
dt = np.dtype(np.int32)

print(dt)

int32


In [14]:
# int8, int16, int32, int64 are equivalent to i1, i2, i4, i8

dt = np.dtype('i1')
print(dt)

int8


In [10]:
dt = np.dtype('i2')
print(dt)

int16


In [11]:
dt = np.dtype('i3')
print(dt)

TypeError: data type 'i3' not understood

In [12]:
dt = np.dtype('i4')
print(dt)

int32


In [13]:
dt = np.dtype('i8')
print(dt)

int64


In [15]:
# using endian notation

dt = np.dtype('>i4')
print(dt)

>i4


In [16]:
dt = np.dtype([('age', np.int8)])
print(dt)

[('age', 'i1')]


In [17]:
# applying to ndarray
dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype = dt)

print(a)

[(10,) (20,) (30,)]


### Numpy Array Attributes

In [18]:
#ndarray.shape

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

(2, 3)


In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.shape)

(3, 3)


In [22]:
#reshaping
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape = (3, 2)
print(a.shape)
print(a)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [23]:
# ndarray.ndim

a = np.array(24)
print(a)

24


In [24]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [25]:
a = np.arange(24)
print(a.ndim)

1


In [26]:
b = a.reshape(2, 3, 4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [27]:
#numpy.itemsize

x = np.array([1, 2, 3, 4, 5], dtype = np.int8)
print(x)

[1 2 3 4 5]


In [28]:
print(x.itemsize)

1


In [29]:
x = np.array([1, 2, 3, 4, 5], dtype = np.float32)
print(x)

[1. 2. 3. 4. 5.]


In [30]:
print(x.itemsize)

4


### Maths with numpy

In [31]:
import math as mth

In [32]:
mth.sqrt(81)

9.0

In [33]:
mth.floor(7.2)

7

In [34]:
mth.ceil(7.2)

8

In [35]:
mth.sin(0)

0.0

In [36]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = ((a - b) ** 2).sum()

mth.sqrt(c)

5.196152422706632