In [4]:
import numpy as np

In [5]:
# They're also called pseudo random numbers
a = np.random.randint(10, 50, 7)

a

array([39, 40, 12, 22, 42, 24, 24])

They're differents sates that the cuputer uses to get random numbers depending the states my system is in. In order to get thesame value's with a different system, we can use the seed function.

In [8]:
# If i want to get thesame values with other person even if tthey're on random
np.random.seed(42)
a = np.random.randint(10, 50, 7)
a

array([48, 38, 24, 17, 30, 48, 28])

### Boroadcasting

In [9]:
b = a + 2
b

array([50, 40, 26, 19, 32, 50, 30])

In [10]:
c = np.array([2])
d = a +c
d

array([50, 40, 26, 19, 32, 50, 30])

In [14]:
A = np.random.randint(2, 7, (2, 3))
A

array([[5, 6, 4],
       [6, 6, 3]])

In [13]:
B = np.random.randint(2, 7, 3)
B

array([5, 3, 6])

In [16]:
A+B

array([[10,  9, 10],
       [11,  9,  9]])

In [17]:
C = np.random.randint(2, 7, 2)

In [18]:
A+C

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### Reshaping
