In [1]:
import numpy as np

In [2]:
scores = np.random.randint(0, 101, (5, 7))
scores

array([[76, 10, 45, 75, 33, 89, 97],
       [29, 24, 23,  4, 25, 39, 89],
       [15, 79, 78, 89, 65, 57, 56],
       [28, 85,  2,  9,  4, 84, 63],
       [40, 82, 99, 36, 81, 96, 31]])

In [3]:
scores.sum()

1837

In [4]:
np.sum(scores)

1837

In [5]:
scores.mean()

52.48571428571429

In [6]:
np.average(scores)

52.48571428571429

In [7]:
scores.ravel()

array([76, 10, 45, 75, 33, 89, 97, 29, 24, 23,  4, 25, 39, 89, 15, 79, 78,
       89, 65, 57, 56, 28, 85,  2,  9,  4, 84, 63, 40, 82, 99, 36, 81, 96,
       31])

In [8]:
scores.mean(axis=0)

array([37.6, 56. , 49.4, 42.6, 41.6, 73. , 67.2])

In [9]:
scores.mean(axis=1)

array([60.71428571, 33.28571429, 62.71428571, 39.28571429, 66.42857143])

In [10]:
x = scores.max(axis=0)
x

array([76, 85, 99, 89, 81, 96, 97])

In [11]:
np.max(x)

99

In [12]:
scores.argmax(axis=0)

array([0, 3, 4, 2, 4, 4, 0], dtype=int64)

In [13]:
scores.argmin(axis=0)

array([2, 0, 3, 1, 3, 1, 4], dtype=int64)

In [14]:
scores[0]

array([76, 10, 45, 75, 33, 89, 97])

In [15]:
scores[1].max()

89

In [16]:
scores[0][1]

10

In [17]:
scores[1].argmax()

6

In [18]:
scores[0, 1]

10

In [19]:
scores[:, 1]

array([10, 24, 79, 85, 82])

In [20]:
scores[:, 0]

array([76, 29, 15, 28, 40])