In [1]:
import numpy as np

In [2]:
scores = np.random.randint(0, 101, (5, 7))
scores

array([[57, 79, 98, 31,  2,  5, 67],
       [88,  7, 22, 21, 48, 42, 86],
       [14, 71, 50, 25, 34, 35, 13],
       [45, 88, 84, 89, 99, 93, 66],
       [64, 24, 22, 91, 51, 43, 68]])

In [3]:
scores.sum()

1822

In [4]:
np.sum(scores)

1822

In [8]:
scores.mean()

52.05714285714286

In [6]:
np.average(scores)

52.05714285714286

In [9]:
scores.ravel()

array([57, 79, 98, 31,  2,  5, 67, 88,  7, 22, 21, 48, 42, 86, 14, 71, 50,
       25, 34, 35, 13, 45, 88, 84, 89, 99, 93, 66, 64, 24, 22, 91, 51, 43,
       68])

In [10]:
scores.mean(axis=0)

array([53.6, 53.8, 55.2, 51.4, 46.8, 43.6, 60. ])

In [11]:
scores.mean(axis=1)

array([48.42857143, 44.85714286, 34.57142857, 80.57142857, 51.85714286])

In [17]:
x = scores.max(axis=0)
x

array([88, 88, 98, 91, 99, 93, 86])

In [18]:
np.max(x)

99

In [20]:
scores.argmax(axis=0)

array([1, 3, 0, 4, 3, 3, 1], dtype=int64)

In [21]:
scores.argmin(axis=0)

array([2, 1, 1, 1, 0, 0, 2], dtype=int64)

In [22]:
scores[0]

array([57, 79, 98, 31,  2,  5, 67])

In [23]:
scores[1].max()

88

In [25]:
scores[0][1]

79

In [26]:
scores[1].argmax()

0

In [27]:
scores[0, 1]

79