### Splitting and stacking of arrays

In [2]:
import numpy as np

In [5]:
x = np.arange(1, 9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
grid = np.arange(16).reshape(4, 4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
lower, upper = np.vsplit(grid, [2])

In [15]:
print('lower:', lower)
print('uper:', upper)

lower: [[0 1 2 3]
 [4 5 6 7]]
uper: [[ 8  9 10 11]
 [12 13 14 15]]


In [18]:
left, right = np.hsplit(grid, [2])
print('left:', left)
print('right:', right)

left: [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right: [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [25]:
x = np.arange(10)
y = np.arange(11, 21)
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]


In [26]:
np.stack((x, y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])