### Data Manipulation with Pandas


In [1]:
import pandas

In [2]:
pandas.__version__

'2.1.1'

In [3]:
import pandas as pd

In [4]:
pd?

Type:        module
String form: <module 'pandas' from 'c:\\Users\\Oxward\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\oxward\appdata\local\programs\python\python311\lib\site-packages\pandas\__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as n

### Introducing Pandas Objects

In [5]:
import numpy as np
import pandas as pd

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.keys

<bound method Series.keys of 0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64>

In [9]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
data[1]

0.5

In [11]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [12]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [13]:
data['b']

0.5

In [14]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [15]:
data[5]

0.5

In [16]:
population_dict = {'Carlifornia': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}
population = pd.Series(population_dict)
population

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
dtype: int64

In [17]:
population['Carlifornia']

38332521

In [18]:
population['Carlifornia': 'Illinois']

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
dtype: int64

In [19]:
pd.Series(data, index=index)

NameError: name 'index' is not defined

In [20]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [21]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [22]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [23]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

### Pandas DataFrame Object

In [24]:
area_dict = {'Carlifornia': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}

In [25]:
area_dict

{'Carlifornia': 423967,
 'Texas': 695662,
 'New York': 141297,
 'Florida': 170312,
 'Illinois': 149995}

In [26]:
area = pd.Series(area_dict)
area

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
dtype: int64

In [27]:
states = pd.DataFrame({'Population': population, 'Area': area})
states

Population    Area
Carlifornia    38332521  423967
Texas          26448193  695662
New York       19651127  141297
Florida        19552860  170312
Illinois       12882135  149995

In [28]:
states.index

Index(['Carlifornia', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [29]:
states.columns

Index(['Population', 'Area'], dtype='object')

In [30]:
states['Area']

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: Area, dtype: int64

In [31]:
states['Population']

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
Name: Population, dtype: int64

In [32]:
pd.DataFrame(population, columns=['population'])

population
Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135

In [33]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [34]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [35]:
pd.DataFrame({'population': population, 'area': area})

population    area
Carlifornia    38332521  423967
Texas          26448193  695662
New York       19651127  141297
Florida        19552860  170312
Illinois       12882135  149995

In [36]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.733296  0.088518
b  0.492949  0.918181
c  0.189463  0.096733

In [37]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [38]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

In [39]:
ind = pd.Index([2, 3, 5, 7 ,11])

ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [40]:
ind[2]

5

In [41]:
ind[1]

3

In [42]:
ind[::3]

Index([2, 7], dtype='int64')

In [43]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [44]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [45]:
ind[1] = 0

TypeError: Index does not support mutable operations

In [ ]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [46]:
indA & indB # intersection

NameError: name 'indA' is not defined

In [47]:
indA | indB # union

NameError: name 'indA' is not defined

In [48]:
indA ^ indB # symmetric difference

NameError: name 'indA' is not defined

In [49]:
indA.intersection(indB)

NameError: name 'indA' is not defined

### Data Indexing and Selection

##### Data Selection in Series

In [50]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [51]:
data['b']

0.5

In [52]:
'a' in data

True

In [53]:
data.keys

<bound method Series.keys of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>

In [54]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [55]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [56]:
data['e'] = 1.25

In [57]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [58]:
# slicing by explicit index

data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [59]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [60]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [61]:
# fancy indexing

data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

##### Indexer's loc, iloc and ix

In [62]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [63]:
# explicit index when indexing
data[1]

'a'

In [64]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [65]:
data.loc[1]

'a'

In [66]:
data.loc[1:3]

1    a
3    b
dtype: object

In [67]:
data.iloc[1]

'b'

In [68]:
data.iloc[1:3]

3    b
5    c
dtype: object

#### Data Selection in DataFrame

##### DataFrame as a dictionary

In [69]:
area = pd.Series({'Carlifornia': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 
                    'Illinois': 149995})

population = pd.Series({'Carlifornia': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135})


In [70]:
data = pd.DataFrame({'area': area, 'pop': population})
data

area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135

In [71]:
data['area']

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [72]:
data['pop']

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
Name: pop, dtype: int64

In [73]:
data.area

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [74]:
data.pop

<bound method DataFrame.pop of                area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135>

In [75]:
data.area is data['area']

True

In [76]:
data.pop is data['pop']

False

In [77]:
data['density'] = data['pop'] / data['area']

In [78]:
data['density']

Carlifornia     90.413926
Texas           38.018740
New York       139.076746
Florida        114.806121
Illinois        85.883763
Name: density, dtype: float64

In [79]:
data

area       pop     density
Carlifornia  423967  38332521   90.413926
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [80]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [81]:
data.T

Carlifornia         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [82]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [83]:
data['area']

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [84]:
data.iloc[:3, :2]

area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127

In [85]:
data.loc[:'Illinois', :'pop']

area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135

In [86]:
data.ix[:3, :'pop']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [87]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [88]:
data.iloc[0, 2] = 90

data

area       pop     density
Carlifornia  423967  38332521   90.000000
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [89]:
data['Florida': 'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [90]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [91]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

#### Operating on Data in Pandas

##### Unfuncs: Index Preservation

In [92]:
import pandas as pd
import numpy as np

In [93]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [94]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['a', 'b', 'c', 'd'])
df

a  b  c  d
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [95]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [96]:
np.sin(df * np.pi / 4)

a             b         c             d
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

##### Unfuncs: Index Alignment

##### Index alignment in series

In [97]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name= 'area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name= 'population')

In [98]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [99]:
area.index | population.index #checking for the union of both of them

TypeError: unsupported operand type(s) for |: 'str' and 'str'

In [100]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [101]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

##### index Alignment in DataFrame

In [102]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [103]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))

B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [104]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [105]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

#### Ufuncs: Operations Between DataFrame and Series

In [106]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [107]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [108]:
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [109]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [110]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [111]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [112]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

### Handling Missing Data

##### Missing data in pandas

##### None: Pythonic missing data

In [113]:
import numpy as np
import pandas as pd

In [114]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [115]:
for dtype in['object', 'int']:
    print('dtype =', dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
69.2 ms ± 2.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
2.37 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [116]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

##### NaN: Missing numerical data

In [ ]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [ ]:
1 + np.nan

nan

In [ ]:
0 * np.nan

nan

In [ ]:
vals2.mean(), vals2.sum(), vals2.max()

(nan, nan, nan)

In [ ]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

##### Nan and None in Pandas

In [ ]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [117]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [118]:
x[0] = None

In [119]:
x

0    NaN
1    1.0
dtype: float64

#### Operating on Null Values

In [121]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [122]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [124]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [125]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [126]:
data.dropna()

0        1
2    hello
dtype: object

In [127]:
df = pd.DataFrame([[1, np.nan, 2],
                    [2, 3, 5],
                    [np.nan, 4, 6]])

df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [128]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [129]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [130]:
df[3] = np.nan

In [131]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [132]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [135]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [136]:
data = pd.Series([1, np.nan, 2, None, 3], index= list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [137]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [138]:
# forward fill
data.fillna(method='ffill')

C:\Users\Oxward\AppData\Local\Temp\ipykernel_14484\3988156040.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [139]:
# back fill
data.fillna(method='bfill')

C:\Users\Oxward\AppData\Local\Temp\ipykernel_14484\3243020708.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')


a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [140]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [141]:
df.fillna(method='ffill', axis=1)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_14484\901808322.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1)


0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

### Hierarchical Indexing

##### Multiple indexed series

In [150]:
Index = [('Carlifornia', 2000), ('Carlifornia', 2010),
        ('New York', 2000), ('New York', 2010),
        ('Texas', 2000), ('Texas', 2010)]
    
porpulations = [33871648, 37253956,
                1876457, 19378102,
                20851820, 25145561]
    
pop = pd.Series(porpulations, index=Index)
pop

(Carlifornia, 2000)    33871648
(Carlifornia, 2010)    37253956
(New York, 2000)        1876457
(New York, 2010)       19378102
(Texas, 2000)          20851820
(Texas, 2010)          25145561
dtype: int64

In [145]:
pop[('Carlifornia', 2010):('Texas', 2000)]

(Carlifornia, 2010)    37253956
(New York, 2000)        1876457
(New York, 2010)       19378102
(Texas, 2000)          20851820
dtype: int64

In [147]:
pop[[i for i in pop.index if i[1] == 2010]]

(Carlifornia, 2010)    37253956
(New York, 2010)       19378102
(Texas, 2010)          25145561
dtype: int64

##### The better way: Pandas multi index

In [151]:
index = pd.MultiIndex.from_tuples(Index)
index

MultiIndex([('Carlifornia', 2000),
            ('Carlifornia', 2010),
            (   'New York', 2000),
            (   'New York', 2010),
            (      'Texas', 2000),
            (      'Texas', 2010)],
           )

In [152]:
pop = pop.reindex(index)
pop

Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
Texas        2000    20851820
             2010    25145561
dtype: int64

In [153]:
pop[:, 2010]

Carlifornia    37253956
New York       19378102
Texas          25145561
dtype: int64

##### MultiIndex as extra dimension

In [154]:
pop_df = pop.unstack()
pop_df

2000      2010
Carlifornia  33871648  37253956
New York      1876457  19378102
Texas        20851820  25145561

In [155]:
pop_df.stack()

Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
Texas        2000    20851820
             2010    25145561
dtype: int64

In [156]:
pop_df = pd.DataFrame({'total': pop,
                        'Under18': [9267089, 9284094,
                                    4687374, 4318033,
                                    5906301, 6879014]})
pop_df

total  Under18
Carlifornia 2000  33871648  9267089
            2010  37253956  9284094
New York    2000   1876457  4687374
            2010  19378102  4318033
Texas       2000  20851820  5906301
            2010  25145561  6879014

In [158]:
f_u18 = pop_df['Under18'] / pop_df['total']

f_u18.unstack()

2000      2010
Carlifornia  0.273594  0.249211
New York     2.497992  0.222831
Texas        0.283251  0.273568

##### Methods of MultiIndex Creation

In [159]:
df = pd.DataFrame(np.random.rand(4, 2),
                index = [['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                columns = ['data1', 'data2'])
        
df

data1     data2
a 1  0.810203  0.178243
  2  0.056706  0.886024
b 1  0.802671  0.962874
  2  0.158774  0.762257

In [160]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [161]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [162]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [163]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [165]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
            labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

TypeError: MultiIndex.__new__() got an unexpected keyword argument 'labels'

In [167]:
pop.index.names = ['state', 'year']

pop

state        year
Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
Texas        2000    20851820
             2010    25145561
dtype: int64

In [168]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                    names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                    names=['subject', 'type'])

In [169]:
# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

In [170]:
# Create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      46.0  36.0  38.0  38.0  16.0  37.0
     2      30.0  37.6  26.0  38.5  28.0  37.5
2014 1      10.0  36.5  35.0  37.3  42.0  36.4
     2      38.0  35.9  43.0  35.6  53.0  37.0

In [171]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      38.0  38.0
     2      26.0  38.5
2014 1      35.0  37.3
     2      43.0  35.6

##### Indexing and Slicing a MultiIndex

In [172]:
pop

state        year
Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
Texas        2000    20851820
             2010    25145561
dtype: int64

In [173]:
pop['Carlifornia', 2000]

33871648

In [175]:
pop['Carlifornia']

year
2000    33871648
2010    37253956
dtype: int64

In [177]:
pop.loc['Carlifornia': 'New York']

state        year
Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
dtype: int64

In [178]:
pop[:, 2000]

state
Carlifornia    33871648
New York        1876457
Texas          20851820
dtype: int64

In [179]:
pop[pop > 22000000]

state        year
Carlifornia  2000    33871648
             2010    37253956
Texas        2010    25145561
dtype: int64

In [180]:
pop[['Carlifornia', 'Texas']]

state        year
Carlifornia  2000    33871648
             2010    37253956
Texas        2000    20851820
             2010    25145561
dtype: int64

##### Multiply indexed DataFrames

In [181]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      46.0  36.0  38.0  38.0  16.0  37.0
     2      30.0  37.6  26.0  38.5  28.0  37.5
2014 1      10.0  36.5  35.0  37.3  42.0  36.4
     2      38.0  35.9  43.0  35.6  53.0  37.0

In [182]:
health_data['Guido', 'HR']

year  visit
2013  1        38.0
      2        26.0
2014  1        35.0
      2        43.0
Name: (Guido, HR), dtype: float64

In [183]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      46.0  36.0
     2      30.0  37.6

In [184]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        46.0
      2        30.0
2014  1        10.0
      2        38.0
Name: (Bob, HR), dtype: float64

In [185]:
health_data.loc[(:, 1), (:, 'HR')]

SyntaxError: invalid syntax (3311942670.py, line 1)

In [186]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      46.0  38.0  16.0
2014 1      10.0  35.0  42.0

In [187]:
index = pd.MultiIndex.from_product([list('abc'), [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['Char', 'Int']
data

Char  Int
a     1      0.224842
      2      0.437244
b     1      0.672918
      2      0.393580
c     1      0.880932
      2      0.530682
dtype: float64

In [190]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

In [191]:
data = data.sort_index()
data

Char  Int
a     1      0.224842
      2      0.437244
b     1      0.672918
      2      0.393580
c     1      0.880932
      2      0.530682
dtype: float64

In [192]:
data['a':'b']

Char  Int
a     1      0.224842
      2      0.437244
b     1      0.672918
      2      0.393580
dtype: float64

In [193]:
pop.unstack(level=0)

state  Carlifornia  New York     Texas
year                                  
2000      33871648   1876457  20851820
2010      37253956  19378102  25145561

In [194]:
pop.unstack(level=1)

year             2000      2010
state                          
Carlifornia  33871648  37253956
New York      1876457  19378102
Texas        20851820  25145561