### Data Manipulation with Pandas


In [1]:
import pandas

In [2]:
pandas.__version__

'2.1.1'

In [3]:
import pandas as pd

In [4]:
pd?

Type:        module
String form: <module 'pandas' from 'c:\\Users\\Oxward\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\oxward\appdata\local\programs\python\python311\lib\site-packages\pandas\__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as n

### Introducing Pandas Objects

In [5]:
import numpy as np
import pandas as pd

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.keys

<bound method Series.keys of 0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64>

In [9]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
data[1]

0.5

In [11]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [12]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [13]:
data['b']

0.5

In [14]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [15]:
data[5]

0.5

In [16]:
population_dict = {'Carlifornia': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}
population = pd.Series(population_dict)
population

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
dtype: int64

In [17]:
population['Carlifornia']

38332521

In [18]:
population['Carlifornia': 'Illinois']

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
dtype: int64

In [19]:
pd.Series(data, index=index)

NameError: name 'index' is not defined

In [20]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [21]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [22]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [23]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

### Pandas DataFrame Object

In [24]:
area_dict = {'Carlifornia': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}

In [25]:
area_dict

{'Carlifornia': 423967,
 'Texas': 695662,
 'New York': 141297,
 'Florida': 170312,
 'Illinois': 149995}

In [26]:
area = pd.Series(area_dict)
area

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
dtype: int64

In [27]:
states = pd.DataFrame({'Population': population, 'Area': area})
states

Population    Area
Carlifornia    38332521  423967
Texas          26448193  695662
New York       19651127  141297
Florida        19552860  170312
Illinois       12882135  149995

In [28]:
states.index

Index(['Carlifornia', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [29]:
states.columns

Index(['Population', 'Area'], dtype='object')

In [30]:
states['Area']

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: Area, dtype: int64

In [31]:
states['Population']

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
Name: Population, dtype: int64

In [32]:
pd.DataFrame(population, columns=['population'])

population
Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135

In [33]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [34]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [35]:
pd.DataFrame({'population': population, 'area': area})

population    area
Carlifornia    38332521  423967
Texas          26448193  695662
New York       19651127  141297
Florida        19552860  170312
Illinois       12882135  149995

In [36]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.966904  0.258838
b  0.372235  0.489014
c  0.194138  0.199904

In [37]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [38]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

In [39]:
ind = pd.Index([2, 3, 5, 7 ,11])

ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [40]:
ind[2]

5

In [41]:
ind[1]

3

In [42]:
ind[::3]

Index([2, 7], dtype='int64')

In [43]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [44]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [45]:
ind[1] = 0

TypeError: Index does not support mutable operations

In [46]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [47]:
indA & indB # intersection

Index([0, 3, 5, 7, 9], dtype='int64')

In [48]:
indA | indB # union

Index([3, 3, 5, 7, 11], dtype='int64')

In [49]:
indA ^ indB # symmetric difference

Index([3, 0, 0, 0, 2], dtype='int64')

In [50]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

### Data Indexing and Selection

##### Data Selection in Series

In [51]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [52]:
data['b']

0.5

In [53]:
'a' in data

True

In [54]:
data.keys

<bound method Series.keys of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>

In [55]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [56]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [57]:
data['e'] = 1.25

In [58]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [59]:
# slicing by explicit index

data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [60]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [61]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [62]:
# fancy indexing

data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

##### Indexer's loc, iloc and ix

In [63]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [64]:
# explicit index when indexing
data[1]

'a'

In [65]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [66]:
data.loc[1]

'a'

In [67]:
data.loc[1:3]

1    a
3    b
dtype: object

In [68]:
data.iloc[1]

'b'

In [69]:
data.iloc[1:3]

3    b
5    c
dtype: object

#### Data Selection in DataFrame

##### DataFrame as a dictionary

In [70]:
area = pd.Series({'Carlifornia': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 
                    'Illinois': 149995})

population = pd.Series({'Carlifornia': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135})


In [71]:
data = pd.DataFrame({'area': area, 'pop': population})
data

area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135

In [72]:
data['area']

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [73]:
data['pop']

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
Name: pop, dtype: int64

In [74]:
data.area

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [75]:
data.pop

<bound method DataFrame.pop of                area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135>

In [76]:
data.area is data['area']

True

In [77]:
data.pop is data['pop']

False

In [78]:
data['density'] = data['pop'] / data['area']

In [79]:
data['density']

Carlifornia     90.413926
Texas           38.018740
New York       139.076746
Florida        114.806121
Illinois        85.883763
Name: density, dtype: float64

In [80]:
data

area       pop     density
Carlifornia  423967  38332521   90.413926
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [81]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [82]:
data.T

Carlifornia         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [83]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [84]:
data['area']

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [85]:
data.iloc[:3, :2]

area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127

In [86]:
data.loc[:'Illinois', :'pop']

area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135

In [87]:
data.ix[:3, :'pop']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [88]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [89]:
data.iloc[0, 2] = 90

data

area       pop     density
Carlifornia  423967  38332521   90.000000
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [90]:
data['Florida': 'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [91]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [92]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

#### Operating on Data in Pandas

##### Unfuncs: Index Preservation

In [93]:
import pandas as pd
import numpy as np

In [94]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [95]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['a', 'b', 'c', 'd'])
df

a  b  c  d
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [96]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [97]:
np.sin(df * np.pi / 4)

a             b         c             d
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

##### Unfuncs: Index Alignment

##### Index alignment in series

In [98]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name= 'area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name= 'population')

In [99]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [100]:
area.index | population.index #checking for the union of both of them

TypeError: unsupported operand type(s) for |: 'str' and 'str'

In [101]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [102]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

##### index Alignment in DataFrame

In [103]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [104]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))

B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [105]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [106]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

#### Ufuncs: Operations Between DataFrame and Series

In [107]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [108]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [109]:
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [110]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [111]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [112]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [113]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

### Handling Missing Data

##### Missing data in pandas

##### None: Pythonic missing data

In [114]:
import numpy as np
import pandas as pd

In [115]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [116]:
for dtype in['object', 'int']:
    print('dtype =', dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
114 ms ± 13.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
3.24 ms ± 547 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [117]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

##### NaN: Missing numerical data

In [118]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [119]:
1 + np.nan

nan

In [120]:
0 * np.nan

nan

In [121]:
vals2.mean(), vals2.sum(), vals2.max()

(nan, nan, nan)

In [122]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

##### Nan and None in Pandas

In [123]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [124]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [125]:
x[0] = None

In [126]:
x

0    NaN
1    1.0
dtype: float64

#### Operating on Null Values

In [127]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [128]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [129]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [130]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [131]:
data.dropna()

0        1
2    hello
dtype: object

In [132]:
df = pd.DataFrame([[1, np.nan, 2],
                    [2, 3, 5],
                    [np.nan, 4, 6]])

df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [133]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [134]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [135]:
df[3] = np.nan

In [136]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [137]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [138]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [139]:
data = pd.Series([1, np.nan, 2, None, 3], index= list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [140]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [141]:
# forward fill
data.fillna(method='ffill')

C:\Users\Oxward\AppData\Local\Temp\ipykernel_14664\3988156040.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [142]:
# back fill
data.fillna(method='bfill')

C:\Users\Oxward\AppData\Local\Temp\ipykernel_14664\3243020708.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')


a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [143]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [144]:
df.fillna(method='ffill', axis=1)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_14664\901808322.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1)


0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

### Hierarchical Indexing

##### Multiple indexed series

In [145]:
Index = [('Carlifornia', 2000), ('Carlifornia', 2010),
        ('New York', 2000), ('New York', 2010),
        ('Texas', 2000), ('Texas', 2010)]
    
porpulations = [33871648, 37253956,
                1876457, 19378102,
                20851820, 25145561]
    
pop = pd.Series(porpulations, index=Index)
pop

(Carlifornia, 2000)    33871648
(Carlifornia, 2010)    37253956
(New York, 2000)        1876457
(New York, 2010)       19378102
(Texas, 2000)          20851820
(Texas, 2010)          25145561
dtype: int64

In [146]:
pop[('Carlifornia', 2010):('Texas', 2000)]

(Carlifornia, 2010)    37253956
(New York, 2000)        1876457
(New York, 2010)       19378102
(Texas, 2000)          20851820
dtype: int64

In [147]:
pop[[i for i in pop.index if i[1] == 2010]]

(Carlifornia, 2010)    37253956
(New York, 2010)       19378102
(Texas, 2010)          25145561
dtype: int64

##### The better way: Pandas multi index

In [148]:
index = pd.MultiIndex.from_tuples(Index)
index

MultiIndex([('Carlifornia', 2000),
            ('Carlifornia', 2010),
            (   'New York', 2000),
            (   'New York', 2010),
            (      'Texas', 2000),
            (      'Texas', 2010)],
           )

In [149]:
pop = pop.reindex(index)
pop

Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
Texas        2000    20851820
             2010    25145561
dtype: int64

In [150]:
pop[:, 2010]

Carlifornia    37253956
New York       19378102
Texas          25145561
dtype: int64

##### MultiIndex as extra dimension

In [151]:
pop_df = pop.unstack()
pop_df

2000      2010
Carlifornia  33871648  37253956
New York      1876457  19378102
Texas        20851820  25145561

In [152]:
pop_df.stack()

Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
Texas        2000    20851820
             2010    25145561
dtype: int64

In [153]:
pop_df = pd.DataFrame({'total': pop,
                        'Under18': [9267089, 9284094,
                                    4687374, 4318033,
                                    5906301, 6879014]})
pop_df

total  Under18
Carlifornia 2000  33871648  9267089
            2010  37253956  9284094
New York    2000   1876457  4687374
            2010  19378102  4318033
Texas       2000  20851820  5906301
            2010  25145561  6879014

In [154]:
f_u18 = pop_df['Under18'] / pop_df['total']

f_u18.unstack()

2000      2010
Carlifornia  0.273594  0.249211
New York     2.497992  0.222831
Texas        0.283251  0.273568

##### Methods of MultiIndex Creation

In [155]:
df = pd.DataFrame(np.random.rand(4, 2),
                index = [['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                columns = ['data1', 'data2'])
        
df

data1     data2
a 1  0.801109  0.094633
  2  0.809892  0.012758
b 1  0.171575  0.703158
  2  0.471233  0.430453

In [156]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [157]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [158]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [159]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [160]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
            labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

TypeError: MultiIndex.__new__() got an unexpected keyword argument 'labels'

In [161]:
pop.index.names = ['state', 'year']

pop

state        year
Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
Texas        2000    20851820
             2010    25145561
dtype: int64

In [162]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                    names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                    names=['subject', 'type'])

In [163]:
# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

In [164]:
# Create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  37.6  29.0  38.2  32.0  39.0
     2      38.0  37.6  36.0  37.3  14.0  38.6
2014 1      43.0  36.2  42.0  38.1  33.0  37.4
     2      22.0  35.3  48.0  36.3  38.0  36.6

In [165]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      29.0  38.2
     2      36.0  37.3
2014 1      42.0  38.1
     2      48.0  36.3

##### Indexing and Slicing a MultiIndex

In [166]:
pop

state        year
Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
Texas        2000    20851820
             2010    25145561
dtype: int64

In [167]:
pop['Carlifornia', 2000]

33871648

In [168]:
pop['Carlifornia']

year
2000    33871648
2010    37253956
dtype: int64

In [169]:
pop.loc['Carlifornia': 'New York']

state        year
Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
dtype: int64

In [170]:
pop[:, 2000]

state
Carlifornia    33871648
New York        1876457
Texas          20851820
dtype: int64

In [171]:
pop[pop > 22000000]

state        year
Carlifornia  2000    33871648
             2010    37253956
Texas        2010    25145561
dtype: int64

In [172]:
pop[['Carlifornia', 'Texas']]

state        year
Carlifornia  2000    33871648
             2010    37253956
Texas        2000    20851820
             2010    25145561
dtype: int64

##### Multiply indexed DataFrames

In [173]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  37.6  29.0  38.2  32.0  39.0
     2      38.0  37.6  36.0  37.3  14.0  38.6
2014 1      43.0  36.2  42.0  38.1  33.0  37.4
     2      22.0  35.3  48.0  36.3  38.0  36.6

In [174]:
health_data['Guido', 'HR']

year  visit
2013  1        29.0
      2        36.0
2014  1        42.0
      2        48.0
Name: (Guido, HR), dtype: float64

In [175]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      40.0  37.6
     2      38.0  37.6

In [176]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        40.0
      2        38.0
2014  1        43.0
      2        22.0
Name: (Bob, HR), dtype: float64

In [177]:
health_data.loc[(:, 1), (:, 'HR')]

SyntaxError: invalid syntax (3311942670.py, line 1)

In [178]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      40.0  29.0  32.0
2014 1      43.0  42.0  33.0

In [179]:
index = pd.MultiIndex.from_product([list('abc'), [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['Char', 'Int']
data

Char  Int
a     1      0.978681
      2      0.655004
b     1      0.343193
      2      0.163924
c     1      0.694605
      2      0.345125
dtype: float64

In [180]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

In [181]:
data = data.sort_index()
data

Char  Int
a     1      0.978681
      2      0.655004
b     1      0.343193
      2      0.163924
c     1      0.694605
      2      0.345125
dtype: float64

In [182]:
data['a':'b']

Char  Int
a     1      0.978681
      2      0.655004
b     1      0.343193
      2      0.163924
dtype: float64

In [183]:
pop.unstack(level=0)

state  Carlifornia  New York     Texas
year                                  
2000      33871648   1876457  20851820
2010      37253956  19378102  25145561

In [184]:
pop.unstack(level=1)

year             2000      2010
state                          
Carlifornia  33871648  37253956
New York      1876457  19378102
Texas        20851820  25145561

In [185]:
pop.unstack().stack()

state        year
Carlifornia  2000    33871648
             2010    37253956
New York     2000     1876457
             2010    19378102
Texas        2000    20851820
             2010    25145561
dtype: int64

In [186]:
pop_flat = pop.reset_index(name='population')

In [187]:
pop_flat

state  year  population
0  Carlifornia  2000    33871648
1  Carlifornia  2010    37253956
2     New York  2000     1876457
3     New York  2010    19378102
4        Texas  2000    20851820
5        Texas  2010    25145561

In [188]:
pop_flat.set_index(['state', 'year'])

population
state       year            
Carlifornia 2000    33871648
            2010    37253956
New York    2000     1876457
            2010    19378102
Texas       2000    20851820
            2010    25145561

#### Data Aggregations on Multi-Indices

In [189]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  37.6  29.0  38.2  32.0  39.0
     2      38.0  37.6  36.0  37.3  14.0  38.6
2014 1      43.0  36.2  42.0  38.1  33.0  37.4
     2      22.0  35.3  48.0  36.3  38.0  36.6

In [190]:
data_mean = health_data.mean()
data_mean

subject  type
Bob      HR      35.750
         Temp    36.675
Guido    HR      38.750
         Temp    37.475
Sue      HR      29.250
         Temp    37.900
dtype: float64

In [191]:
data_mean.mean(axis=1, level='type')

TypeError: mean() got an unexpected keyword argument 'level'

##### Combining Datasets: Concat and Append

In [207]:
import numpy as np
import pandas as pd

In [208]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
                for c in cols}
    return pd.DataFrame(data, ind)


# example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

#### Recall: Concatenation of NumPy Arrays

In [209]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
x = [[1, 2],
    [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

#### Simple Concatenation with pd.concat

In [211]:
# Signature in Pandas v0.18

pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None,
            names=None, verify_integrity=False, copy=True)

NameError: name 'objs' is not defined

In [212]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [213]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1); print(df2); print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [214]:
df3 = make_df('AB', [0, 1])
df4 = make_df('AB', [0, 1])
print(df3); print(df4); print(pd.concat([df3, df4], axis='col'))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A0  B0
1  A1  B1


ValueError: No axis named col for object type DataFrame

In [215]:
df3 = make_df('AB', [0, 1])
df4 = make_df('AB', [0, 1])
print(df3); print(df4); print(pd.concat([df3, df4], axis=1))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A0  B0
1  A1  B1
    A   B   A   B
0  A0  B0  A0  B0
1  A1  B1  A1  B1


In [216]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

y.index = x.index # make duplicate indicies!
print(x); print(y); print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [217]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print('ValueError:', e)

ValueError: Indexes have overlapping values: Index([0, 1], dtype='int64')


In [218]:
print(x); print(y); print(pd.concat([x, y], ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [219]:
print(x); print(y); print(pd.concat([x, y], keys=['x', 'y']))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3


In [220]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5); print(df6); print(pd.concat([df5, df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


In [221]:
print(df5); print(df6);
print(pd.concat([df5, df6], join='inner'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [222]:
print(df5); print(df6);
print(pd.concat([df5, df6], join_axes=[df.columns]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4


TypeError: concat() got an unexpected keyword argument 'join_axes'

In [223]:
print(df1); print(df2); print(df1.append(df2))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4


AttributeError: 'DataFrame' object has no attribute 'append'

### Combining Datasets: Merge and Join

#### Relational Algebra

##### Categories of Joins

###### One-to-one joins

In [224]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})

df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
        
print(df1); print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [225]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

#### Many-to-one joins

In [226]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3); print(df4); print(pd.merge(df3, df4))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


In [227]:
print(pd.merge(df3, df4))

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve


#### Mant-to-many joins

In [228]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux', 'spreadsheets', 'organization']})
    
print(df1); print(df5); print(pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization


##### The on keyword

In [229]:
print(df1); print(df2); print(pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [230]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
                
print(df1); print(df3);
print(pd.merge(df1, df3, left_on='employee', right_on='name'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000


In [231]:
pd.merge(df1, df3, left_on='employee', right_on='name').drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [232]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a); print(df2a)

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


In [233]:
print(df1a); print(df2a);
print(pd.merge(df1a, df2a, left_index=True, right_index=True))

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014
                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014


In [234]:
print(df1a); print(df2a); print(df1a.join(df2a))

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014
                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014


In [235]:
print(df1a); print(df3);
print(pd.merge(df1a, df3, left_index=True, right_on='name'))

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000


### Specifying Set Arithmetic for Joins

In [236]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                    columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                    columns=['name', 'drink'])
print(df6); print(df7); print(pd.merge(df6, df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
   name   food drink
0  Mary  bread  wine


In [237]:
pd.merge(df6, df7, how='inner')

name   food drink
0  Mary  bread  wine

In [238]:
pd.merge(df6, df7, how='outer')

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [239]:
pd.merge(df6, df7, how='left')

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [240]:
pd.merge(df6, df7, how='right')

name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

#### Overlapping Column Names: The suffixes Keyword

In [242]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'], 'rank': [1, 2, 3, 4]})

df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'], 'rank': [3, 1, 4, 2]})

print(df8); print(df9); print(pd.merge(df8, df9, on='name'))

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2
   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2


In [243]:
print(pd.merge(df8, df9, on='name'))

   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2


In [244]:
print(pd.merge(df8, df9, on='name', suffixes=['_L', '_R']))

   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2


### Example: US States Data

In [251]:
pop = pd.read_csv('data/state-population.csv')
areas = pd.read_csv('data/state-areas.csv')
abbrevs = pd.read_csv('data/state-abbrevs.csv')

print(pop.head()); print(areas.head()); print(abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA


In [253]:
merged = pd.merge(pop, abbrevs, how='outer',
                left_on='state/region', right_on='abbreviation')
                
merged = merged.drop('abbreviation', 1) # drop duplicate info
merged.head()

TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 were given