### Data Manipulation with Pandas


In [1]:
import pandas

In [2]:
pandas.__version__

'2.1.1'

In [3]:
import pandas as pd

In [4]:
pd?

Type:        module
String form: <module 'pandas' from 'c:\\Users\\Oxward\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\oxward\appdata\local\programs\python\python311\lib\site-packages\pandas\__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as n

### Introducing Pandas Objects

In [5]:
import numpy as np
import pandas as pd

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.keys

<bound method Series.keys of 0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64>

In [9]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
data[1]

0.5

In [11]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [12]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [13]:
data['b']

0.5

In [14]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [15]:
data[5]

0.5

In [16]:
population_dict = {'Carlifornia': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}
population = pd.Series(population_dict)
population

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
dtype: int64

In [17]:
population['Carlifornia']

38332521

In [18]:
population['Carlifornia': 'Illinois']

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
dtype: int64

In [19]:
pd.Series(data, index=index)

NameError: name 'index' is not defined

In [20]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [21]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [22]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [23]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

### Pandas DataFrame Object

In [24]:
area_dict = {'Carlifornia': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}

In [25]:
area_dict

{'Carlifornia': 423967,
 'Texas': 695662,
 'New York': 141297,
 'Florida': 170312,
 'Illinois': 149995}

In [26]:
area = pd.Series(area_dict)
area

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
dtype: int64

In [27]:
states = pd.DataFrame({'Population': population, 'Area': area})
states

Population    Area
Carlifornia    38332521  423967
Texas          26448193  695662
New York       19651127  141297
Florida        19552860  170312
Illinois       12882135  149995

In [28]:
states.index

Index(['Carlifornia', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [29]:
states.columns

Index(['Population', 'Area'], dtype='object')

In [30]:
states['Area']

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: Area, dtype: int64

In [31]:
states['Population']

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
Name: Population, dtype: int64

In [32]:
pd.DataFrame(population, columns=['population'])

population
Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135

In [33]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [34]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [35]:
pd.DataFrame({'population': population, 'area': area})

population    area
Carlifornia    38332521  423967
Texas          26448193  695662
New York       19651127  141297
Florida        19552860  170312
Illinois       12882135  149995

In [36]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.302965  0.642425
b  0.812375  0.918502
c  0.875170  0.975938

In [37]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [38]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

In [39]:
ind = pd.Index([2, 3, 5, 7 ,11])

ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [40]:
ind[2]

5

In [41]:
ind[1]

3

In [42]:
ind[::3]

Index([2, 7], dtype='int64')

In [43]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [44]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [45]:
ind[1] = 0

TypeError: Index does not support mutable operations

In [48]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [49]:
indA & indB # intersection

Index([0, 3, 5, 7, 9], dtype='int64')

In [50]:
indA | indB # union

Index([3, 3, 5, 7, 11], dtype='int64')

In [51]:
indA ^ indB # symmetric difference

Index([3, 0, 0, 0, 2], dtype='int64')

In [52]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

### Data Indexing and Selection

##### Data Selection in Series

In [53]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [54]:
data['b']

0.5

In [55]:
'a' in data

True

In [56]:
data.keys

<bound method Series.keys of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>

In [57]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [59]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [60]:
data['e'] = 1.25

In [61]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [62]:
# slicing by explicit index

data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [63]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [65]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [67]:
# fancy indexing

data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

##### Indexer's loc, iloc and ix

In [68]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [69]:
# explicit index when indexing
data[1]

'a'

In [70]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [71]:
data.loc[1]

'a'

In [72]:
data.loc[1:3]

1    a
3    b
dtype: object

In [73]:
data.iloc[1]

'b'

In [74]:
data.iloc[1:3]

3    b
5    c
dtype: object

#### Data Selection in DataFrame

##### DataFrame as a dictionary

In [75]:
area = pd.Series({'Carlifornia': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 
                    'Illinois': 149995})

population = pd.Series({'Carlifornia': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135})


In [76]:
data = pd.DataFrame({'area': area, 'pop': population})
data

area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135

In [77]:
data['area']

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [78]:
data['pop']

Carlifornia    38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135
Name: pop, dtype: int64

In [79]:
data.area

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [80]:
data.pop

<bound method DataFrame.pop of                area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135>

In [81]:
data.area is data['area']

True

In [82]:
data.pop is data['pop']

False

In [83]:
data['density'] = data['pop'] / data['area']

In [84]:
data['density']

Carlifornia     90.413926
Texas           38.018740
New York       139.076746
Florida        114.806121
Illinois        85.883763
Name: density, dtype: float64

In [85]:
data

area       pop     density
Carlifornia  423967  38332521   90.413926
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [86]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [87]:
data.T

Carlifornia         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [88]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [89]:
data['area']

Carlifornia    423967
Texas          695662
New York       141297
Florida        170312
Illinois       149995
Name: area, dtype: int64

In [90]:
data.iloc[:3, :2]

area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127

In [93]:
data.loc[:'Illinois', :'pop']

area       pop
Carlifornia  423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135

In [95]:
data.ix[:3, :'pop']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [96]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [98]:
data.iloc[0, 2] = 90

data

area       pop     density
Carlifornia  423967  38332521   90.000000
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [99]:
data['Florida': 'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [100]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [101]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

#### Operating on Data in Pandas

##### Unfuncs: Index Preservation

In [1]:
import pandas as pd
import numpy as np

In [2]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [3]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['a', 'b', 'c', 'd'])
df

a  b  c  d
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [4]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [5]:
np.sin(df * np.pi / 4)

a             b         c             d
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

##### Unfuncs: Index Alignment

##### Index alignment in series

In [6]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name= 'area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name= 'population')

In [7]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [8]:
area.index | population.index #checking for the union of both of them

TypeError: unsupported operand type(s) for |: 'str' and 'str'

In [10]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [11]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

##### index Alignment in DataFrame

In [13]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [14]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))

B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [15]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [17]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

#### Ufuncs: Operations Between DataFrame and Series

In [18]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [19]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [20]:
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [21]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [22]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [23]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [24]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

### Handling Missing Data