In [1]:
a = [2, 3, 5, 4]
b = [1, -3, 4, 9]

c = list(map(lambda x, y: x + y, a, b))

c


[3, 0, 9, 13]

In [2]:
c = []

for i in range(len(a)):
    c.append(a[i] + b[i])

c

[3, 0, 9, 13]

In [3]:
list(zip(a, b))

[(2, 1), (3, -3), (5, 4), (4, 9)]

In [4]:
c = []

for item in zip(a, b):
    c.append(item[0] + item[1])

c

[3, 0, 9, 13]

In [5]:
c = []

for item in zip(a, b):
    c.append(sum(item))

c

[3, 0, 9, 13]

In [6]:
c = []

for x, y in zip(a, b):
    c.append(x + y)

c

[3, 0, 9, 13]

### Working with Numpy

In [7]:
import numpy as np

In [10]:
# convert a list or turple to Numpy array

a = [2, 3, 5, 4]
b = [1, -3, 4, 9]

a = np.array(a)
b = np.array(b)

c = a + b

print(a)
print(b)
print(c)
c


[2 3 5 4]
[ 1 -3  4  9]
[ 3  0  9 13]


array([ 3,  0,  9, 13])

In [11]:
d = a * b
print(d)
d

[ 2 -9 20 36]


array([ 2, -9, 20, 36])

In [12]:
e = b**2

e

array([ 1,  9, 16, 81])

In [13]:
f = 4 * a

f

array([ 8, 12, 20, 16])

### Numpy artributes

In [16]:
print(a.ndim) # a is a one dimensional array

1


In [17]:
print(a.size) # the len of te element

4


In [18]:
print(a.dtype)

int32


In [19]:
c = np.array([2, 4, 9, 3.2])
print(c.dtype)

float64


In [20]:
c

array([2. , 4. , 9. , 3.2])

In [21]:
print(c)

[2.  4.  9.  3.2]


In [22]:
c = np.array([2, 4, 9, 3.2, 'test'])
print(c.dtype)

<U32


In [23]:
c

array(['2', '4', '9', '3.2', 'test'], dtype='<U32')

In [24]:
c.shape

(5,)

In [29]:
## Two dimensional arrays

x = np.array([[4, 9], [7, 2], [1.4, 1]])

x

array([[4. , 9. ],
       [7. , 2. ],
       [1.4, 1. ]])

In [30]:
x.size

6

In [31]:
print(x.size)

6


In [32]:
print(x.ndim)

2


In [33]:
print(x.dtype)

float64


In [34]:
print(x.shape)

(3, 2)


In [36]:
a = np.arange(5)
b = np.arange(4, 8, 1.2)

print(a)
print(b)

[0 1 2 3 4]
[4.  5.2 6.4 7.6]


In [37]:
c = np.linspace(10, 40)

c

array([10.        , 10.6122449 , 11.2244898 , 11.83673469, 12.44897959,
       13.06122449, 13.67346939, 14.28571429, 14.89795918, 15.51020408,
       16.12244898, 16.73469388, 17.34693878, 17.95918367, 18.57142857,
       19.18367347, 19.79591837, 20.40816327, 21.02040816, 21.63265306,
       22.24489796, 22.85714286, 23.46938776, 24.08163265, 24.69387755,
       25.30612245, 25.91836735, 26.53061224, 27.14285714, 27.75510204,
       28.36734694, 28.97959184, 29.59183673, 30.20408163, 30.81632653,
       31.42857143, 32.04081633, 32.65306122, 33.26530612, 33.87755102,
       34.48979592, 35.10204082, 35.71428571, 36.32653061, 36.93877551,
       37.55102041, 38.16326531, 38.7755102 , 39.3877551 , 40.        ])

In [38]:
c.shape

(50,)

In [39]:
c.size

50

In [40]:
30/49

0.6122448979591837

In [41]:
c = np.linspace(10, 40, 15)

c

array([10.        , 12.14285714, 14.28571429, 16.42857143, 18.57142857,
       20.71428571, 22.85714286, 25.        , 27.14285714, 29.28571429,
       31.42857143, 33.57142857, 35.71428571, 37.85714286, 40.        ])

In [42]:
# How do you use random in numpy to randomly generate values

# How to reshape an array


x = np.random.randint(1, 100)

x

64

In [45]:
x = np.random.randint(1, 100, 20)

x

array([22, 23, 43, 17,  6, 18, 83, 97, 18, 25,  9, 48, 77, 21, 79, 59, 76,
       56, 37, 88])

In [51]:
y = np.array([[1, 2, 3], [4, 5, 6]])

y.shape

(2, 3)

In [52]:
y.reshape(3, 2)

y

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
z = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

z.shape

(5, 2)

In [54]:
q = z.reshape(2, 5)

q

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])