In [1]:
a = [2, 3, 5, 4]
b = [1, -3, 4, 9]

c = list(map(lambda x, y: x + y, a, b))

c


[3, 0, 9, 13]

In [2]:
c = []

for i in range(len(a)):
    c.append(a[i] + b[i])

c

[3, 0, 9, 13]

In [3]:
list(zip(a, b))

[(2, 1), (3, -3), (5, 4), (4, 9)]

In [4]:
c = []

for item in zip(a, b):
    c.append(item[0] + item[1])

c

[3, 0, 9, 13]

In [5]:
c = []

for item in zip(a, b):
    c.append(sum(item))

c

[3, 0, 9, 13]

In [6]:
c = []

for x, y in zip(a, b):
    c.append(x + y)

c

[3, 0, 9, 13]

### Working with Numpy

In [7]:
import numpy as np

In [10]:
# convert a list or turple to Numpy array

a = [2, 3, 5, 4]
b = [1, -3, 4, 9]

a = np.array(a)
b = np.array(b)

c = a + b

print(a)
print(b)
print(c)
c


[2 3 5 4]
[ 1 -3  4  9]
[ 3  0  9 13]


array([ 3,  0,  9, 13])

In [11]:
d = a * b
print(d)
d

[ 2 -9 20 36]


array([ 2, -9, 20, 36])

In [12]:
e = b**2

e

array([ 1,  9, 16, 81])

In [13]:
f = 4 * a

f

array([ 8, 12, 20, 16])

### Numpy artributes

In [16]:
print(a.ndim) # a is a one dimensional array

1


In [17]:
print(a.size) # the len of te element

4


In [18]:
print(a.dtype)

int32


In [19]:
c = np.array([2, 4, 9, 3.2])
print(c.dtype)

float64


In [20]:
c

array([2. , 4. , 9. , 3.2])

In [21]:
print(c)

[2.  4.  9.  3.2]


In [22]:
c = np.array([2, 4, 9, 3.2, 'test'])
print(c.dtype)

<U32


In [23]:
c

array(['2', '4', '9', '3.2', 'test'], dtype='<U32')

In [24]:
c.shape

(5,)

In [29]:
## Two dimensional arrays

x = np.array([[4, 9], [7, 2], [1.4, 1]])

x

array([[4. , 9. ],
       [7. , 2. ],
       [1.4, 1. ]])

In [30]:
x.size

6

In [31]:
print(x.size)

6


In [32]:
print(x.ndim)

2


In [33]:
print(x.dtype)

float64


In [34]:
print(x.shape)

(3, 2)


In [36]:
a = np.arange(5)
b = np.arange(4, 8, 1.2)

print(a)
print(b)

[0 1 2 3 4]
[4.  5.2 6.4 7.6]
