In [1]:
import numpy 

In [2]:
numpy.__version__

'1.26.1'

In [3]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [5]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\Oxward\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\oxward\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippe

In [6]:
result = 0
for i in range(100):
    result += i

result

4950

In [7]:
x = 4

In [8]:
x = 'four'

In [9]:
l = list(range(10))

In [10]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
type(l[0])

int

In [13]:
L2 = [str(c) for c in l]

L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [14]:
type(L2[0])

str

In [15]:
L3 = [True, '2', 2.0, 4]

In [16]:
[type(item) for item in L3]

[bool, str, float, int]

In [17]:
import array

In [18]:
L = list(range(10))
A = array.array('i', L)

A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
import numpy as np

In [22]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [23]:
np.array([3.4, 2, 5, 7, 6])

array([3.4, 2. , 5. , 7. , 6. ])

In [24]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [25]:
# nested list result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [26]:
# Creating a length-10 inter array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.ones(15, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
# Creating a 3x5 floating-point array filled with 1s

np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# creating a 3x5 array filed with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [30]:
# Creating an array filled with linear sequence
# Starting at 0, ending at 20, stpping by 2
# This is similar to range function

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
# Creating an array of five values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
# Create a 3x3 array of uniform distributed
# random values between 0 and 1

np.random.random((3, 3))

array([[0.97142258, 0.07569872, 0.26402249],
       [0.01862753, 0.03228402, 0.87355482],
       [0.07094836, 0.1201907 , 0.55877228]])

In [33]:
# creating a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0, 1, (3, 3))

array([[ 0.42032621, -0.82874428, -0.39575142],
       [-0.51009933, -0.23874043,  0.98431514],
       [-0.03899462,  0.21586559, -0.52494712]])

In [34]:
# Creating a 3x3 array of random integers in the interval[0, 10]

np.random.randint(0, 10, (3, 3))

array([[1, 8, 6],
       [5, 1, 9],
       [6, 5, 0]])

In [35]:
# Creating a 3x3 identical matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# Creating an uninitilized array of three integers
# the values will be what ever happens to already exist at that
# momory location

np.empty((3))

array([1., 1., 1.])

In [37]:
np.empty(3)

array([1., 1., 1.])

In [38]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [39]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## Numpy attributes

In [40]:
np.random.seed(0) #Seed for reproducibility

In [41]:
x1 = np.random.randint(10, size=6) # one dimensional array
x2 = np.random.randint(10, size=(3, 4)) # two dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # three dimensioanl array

Each array has attributes ndim (the number of dimensions), shape (the size of each
dimension), and size (the total size of the array)

In [42]:
print('x3 ndim: ', x3.ndim)
print('x3 size: ', x3.size)
print('x3 shape: ', x3.shape)

x3 ndim:  3
x3 size:  60
x3 shape:  (3, 4, 5)


In [44]:
print('data type: ', x3.dtype)

data type:  int32


In [45]:
print('item size: ', x3.itemsize)

item size:  4


In [47]:
print('nbytes: ', x3.nbytes, ' bytes')

nbytes:  240  bytes


In [50]:
60 * 4 # the nbytes must be equal to item size * size

240