In [1]:
import numpy 

In [2]:
numpy.__version__

'1.26.1'

In [3]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [5]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\Oxward\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\oxward\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippe

In [6]:
result = 0
for i in range(100):
    result += i

result

4950

In [7]:
x = 4

In [8]:
x = 'four'

In [9]:
l = list(range(10))

In [10]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
type(l[0])

int

In [12]:
L2 = [str(c) for c in l]

L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(L2[0])

str

In [14]:
L3 = [True, '2', 2.0, 4]

In [15]:
[type(item) for item in L3]

[bool, str, float, int]

In [16]:
import array

In [17]:
L = list(range(10))
A = array.array('i', L)

A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
import numpy as np

In [21]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [22]:
np.array([3.4, 2, 5, 7, 6])

array([3.4, 2. , 5. , 7. , 6. ])

In [23]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [24]:
# nested list result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [25]:
# Creating a length-10 inter array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones(15, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
# Creating a 3x5 floating-point array filled with 1s

np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# creating a 3x5 array filed with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
# Creating an array filled with linear sequence
# Starting at 0, ending at 20, stpping by 2
# This is similar to range function

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# Creating an array of five values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
# Create a 3x3 array of uniform distributed
# random values between 0 and 1

np.random.random((3, 3))

array([[0.50359052, 0.84941761, 0.00283674],
       [0.41504965, 0.84859525, 0.92026859],
       [0.92104477, 0.08365853, 0.34609126]])

In [32]:
# creating a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0, 1, (3, 3))

array([[-0.69978594, -1.47671031,  0.90537029],
       [ 0.47710499, -0.36752208, -0.44198182],
       [-1.94142938,  1.33238432,  1.15110784]])

In [33]:
# Creating a 3x3 array of random integers in the interval[0, 10]

np.random.randint(0, 10, (3, 3))

array([[7, 0, 8],
       [1, 3, 1],
       [2, 5, 2]])

In [34]:
# Creating a 3x3 identical matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# Creating an uninitilized array of three integers
# the values will be what ever happens to already exist at that
# momory location

np.empty((3))

array([1., 1., 1.])

In [36]:
np.empty(3)

array([1., 1., 1.])

In [37]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [38]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## Numpy attributes

In [39]:
np.random.seed(0) #Seed for reproducibility

In [40]:
x1 = np.random.randint(10, size=6) # one dimensional array
x2 = np.random.randint(10, size=(3, 4)) # two dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # three dimensioanl array

Each array has attributes ndim (the number of dimensions), shape (the size of each
dimension), and size (the total size of the array)

In [41]:
print('x3 ndim: ', x3.ndim)
print('x3 size: ', x3.size)
print('x3 shape: ', x3.shape)

x3 ndim:  3
x3 size:  60
x3 shape:  (3, 4, 5)


In [42]:
print('data type: ', x3.dtype)

data type:  int32


In [43]:
print('item size: ', x3.itemsize)

item size:  4


In [44]:
print('nbytes: ', x3.nbytes, ' bytes')

nbytes:  240  bytes


In [45]:
60 * 4 # the nbytes must be equal to item size * size

240

In [46]:
x1

array([5, 0, 3, 3, 7, 9])

In [47]:
x1[0]

5

In [48]:
x1[4]

7

In [49]:
x1[5]

9

In [50]:
x1[-1]

9

In [51]:
x1[-2]

7

In [52]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [53]:
x2[0, 0]

3

In [54]:
x2[2, 0]

1

In [55]:
x2[1, 3]

8

In [56]:
x2[2, -1]

7

In [57]:
x2[0, 0] = 12

In [58]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [61]:
x1[0] = 3.14567 # this will be truncated!

In [62]:
x1

array([3, 0, 3, 3, 7, 9])

In [64]:
# x[start:stop:step]

In [66]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x[:5] # the first five elements

array([0, 1, 2, 3, 4])

In [68]:
x[3:] #the numbers from the fourth element

array([3, 4, 5, 6, 7, 8, 9])

In [69]:
x[2:5:2] #starting with the third element to the fifth elemnt with a skip of two steps

array([2, 4])

In [71]:
x[2::2] # starting from the third element to the last with a step of 2

array([2, 4, 6, 8])

In [72]:
x[4:7] # midle sub-array

array([4, 5, 6])

In [73]:
x[::2] # every other elements

array([0, 2, 4, 6, 8])

In [74]:
x[1::2] # every other elements starting with index 1

array([1, 3, 5, 7, 9])

In [75]:
x[::-1] # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [76]:
x[5::-2] # reverse of every other elements from index of 5

array([5, 3, 1])

In [77]:
# Multidimensional sub array's

x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [78]:
x2[:2, :3] # two rows three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [79]:
x2[:3, ::2] # all rows every other columns

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [80]:
x2[::-1, ::-1] # sub arrays can also be substracted together

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [81]:
print(x2[:, 0]) #first column of x2

[12  7  1]


In [82]:
print(x2[0, :]) #first row of x2

[12  5  2  4]


In [83]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


In [84]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [85]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [86]:
x2_sub[0, 0] = 99

x2_sub

array([[99,  5],
       [ 7,  6]])

In [87]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [89]:
# reshaping

grid = np.arange(1, 10).reshape((3, 3))

grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
x = np.array([1, 2, 3])

x

array([1, 2, 3])

In [91]:
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [92]:
# row vector via new axis

x[np.newaxis, :]

array([[1, 2, 3]])

In [93]:
# column vectoer via reshape

x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [95]:
# Concatinaton of arrays

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [96]:
# you can also concatinate more than two arrays at once

z = np.array([7, 8, 9])
v = np.array([4, 5, 6])

np.concatenate([x, y, z, v])

array([1, 2, 3, 3, 2, 1, 7, 8, 9, 4, 5, 6])

In [98]:
# np.concatenate can also be used for two-dimensonal arrays

grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [100]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [101]:
# For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) 
# and np.hstack (horizontal stack) functions

x = np.array([1, 2, 3])

grid = np.array([[4, 5, 6], [7, 8, 9]])

In [102]:
# vertically stack the arrays

np.vstack([x, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
# horizontally stack the arrays

y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

In [108]:
# np.dstack will stack arrays along the third axis


In [109]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])

In [110]:
x1

array([1, 2, 3])

In [111]:
x2

array([99, 99])

In [112]:
x3

array([3, 2, 1])

In [113]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [114]:
grid = np.arange(16).reshape((4, 4))

grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
upper, lower = np.vsplit(grid, [2])

print(f'upper: {upper}')
print(f'lower: {lower}')

upper: [[0 1 2 3]
 [4 5 6 7]]
lower: [[ 8  9 10 11]
 [12 13 14 15]]


In [119]:
left, right = np.hsplit(grid, [2])

print(f'left: {left}')
print(f'right: {right}')

left: [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right: [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
