In [1]:
import numpy as np

In [2]:
# How do you use random in numpy to randomly generate values

# How to reshape an array


x = np.random.randint(1, 100)

x

59

In [3]:
x = np.random.randint(1, 100, 20)

x

array([ 8, 42, 19, 70, 18, 25, 54, 16, 81,  7, 98, 40, 75, 99, 70, 86, 92,
       96, 91, 22])

In [4]:
y = np.array([[1, 2, 3], [4, 5, 6]])

y.shape

(2, 3)

In [5]:
y.reshape(3, 2)

y

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
z = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

z.shape

(5, 2)

In [7]:
q = z.reshape(2, 5)

q

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])