In [1]:
import numpy 

In [2]:
numpy.__version__

'1.26.1'

In [3]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [5]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\Oxward\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\oxward\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippe

In [6]:
result = 0
for i in range(100):
    result += i

result

4950

In [7]:
x = 4

In [8]:
x = 'four'

In [9]:
l = list(range(10))

In [10]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
type(l[0])

int

In [12]:
L2 = [str(c) for c in l]

L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(L2[0])

str

In [14]:
L3 = [True, '2', 2.0, 4]

In [15]:
[type(item) for item in L3]

[bool, str, float, int]

In [16]:
import array

In [17]:
L = list(range(10))
A = array.array('i', L)

A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
import numpy as np

In [21]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [22]:
np.array([3.4, 2, 5, 7, 6])

array([3.4, 2. , 5. , 7. , 6. ])

In [23]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [24]:
# nested list result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [25]:
# Creating a length-10 inter array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones(15, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
# Creating a 3x5 floating-point array filled with 1s

np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# creating a 3x5 array filed with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
# Creating an array filled with linear sequence
# Starting at 0, ending at 20, stpping by 2
# This is similar to range function

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# Creating an array of five values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
# Create a 3x3 array of uniform distributed
# random values between 0 and 1

np.random.random((3, 3))

array([[0.95246422, 0.45625598, 0.93755933],
       [0.08096376, 0.91518377, 0.09625242],
       [0.27444097, 0.59064389, 0.4754741 ]])

In [32]:
# creating a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0, 1, (3, 3))

array([[-0.90393533,  1.88445118,  0.55568986],
       [ 1.5935229 ,  0.36726602, -1.02023187],
       [ 0.59692078,  0.51605929,  0.97393675]])

In [33]:
# Creating a 3x3 array of random integers in the interval[0, 10]

np.random.randint(0, 10, (3, 3))

array([[7, 9, 6],
       [8, 5, 8],
       [8, 3, 7]])

In [34]:
# Creating a 3x3 identical matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# Creating an uninitilized array of three integers
# the values will be what ever happens to already exist at that
# momory location

np.empty((3))

array([1., 1., 1.])

In [36]:
np.empty(3)

array([1., 1., 1.])

In [37]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [38]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## Numpy attributes

In [39]:
np.random.seed(0) #Seed for reproducibility

In [40]:
x1 = np.random.randint(10, size=6) # one dimensional array
x2 = np.random.randint(10, size=(3, 4)) # two dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # three dimensioanl array

Each array has attributes ndim (the number of dimensions), shape (the size of each
dimension), and size (the total size of the array)

In [41]:
print('x3 ndim: ', x3.ndim)
print('x3 size: ', x3.size)
print('x3 shape: ', x3.shape)

x3 ndim:  3
x3 size:  60
x3 shape:  (3, 4, 5)


In [42]:
print('data type: ', x3.dtype)

data type:  int32


In [43]:
print('item size: ', x3.itemsize)

item size:  4


In [44]:
print('nbytes: ', x3.nbytes, ' bytes')

nbytes:  240  bytes


In [45]:
60 * 4 # the nbytes must be equal to item size * size

240

In [46]:
x1

array([5, 0, 3, 3, 7, 9])

In [47]:
x1[0]

5

In [48]:
x1[4]

7

In [49]:
x1[5]

9

In [50]:
x1[-1]

9

In [51]:
x1[-2]

7

In [52]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [53]:
x2[0, 0]

3

In [54]:
x2[2, 0]

1

In [55]:
x2[1, 3]

8

In [56]:
x2[2, -1]

7

In [57]:
x2[0, 0] = 12

In [58]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [59]:
x1[0] = 3.14567 # this will be truncated!

In [60]:
x1

array([3, 0, 3, 3, 7, 9])

In [61]:
# x[start:stop:step]

In [62]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
x[:5] # the first five elements

array([0, 1, 2, 3, 4])

In [64]:
x[3:] #the numbers from the fourth element

array([3, 4, 5, 6, 7, 8, 9])

In [65]:
x[2:5:2] #starting with the third element to the fifth elemnt with a skip of two steps

array([2, 4])

In [66]:
x[2::2] # starting from the third element to the last with a step of 2

array([2, 4, 6, 8])

In [67]:
x[4:7] # midle sub-array

array([4, 5, 6])

In [68]:
x[::2] # every other elements

array([0, 2, 4, 6, 8])

In [69]:
x[1::2] # every other elements starting with index 1

array([1, 3, 5, 7, 9])

In [70]:
x[::-1] # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [71]:
x[5::-2] # reverse of every other elements from index of 5

array([5, 3, 1])

In [72]:
# Multidimensional sub array's

x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [73]:
x2[:2, :3] # two rows three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [74]:
x2[:3, ::2] # all rows every other columns

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [75]:
x2[::-1, ::-1] # sub arrays can also be substracted together

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [76]:
print(x2[:, 0]) #first column of x2

[12  7  1]


In [77]:
print(x2[0, :]) #first row of x2

[12  5  2  4]


In [78]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


In [79]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [80]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [81]:
x2_sub[0, 0] = 99

x2_sub

array([[99,  5],
       [ 7,  6]])

In [82]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [83]:
# reshaping

grid = np.arange(1, 10).reshape((3, 3))

grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
x = np.array([1, 2, 3])

x

array([1, 2, 3])

In [85]:
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [86]:
# row vector via new axis

x[np.newaxis, :]

array([[1, 2, 3]])

In [87]:
# column vectoer via reshape

x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [88]:
# Concatinaton of arrays

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [89]:
# you can also concatinate more than two arrays at once

z = np.array([7, 8, 9])
v = np.array([4, 5, 6])

np.concatenate([x, y, z, v])

array([1, 2, 3, 3, 2, 1, 7, 8, 9, 4, 5, 6])

In [90]:
# np.concatenate can also be used for two-dimensonal arrays

grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [92]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [93]:
# For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) 
# and np.hstack (horizontal stack) functions

x = np.array([1, 2, 3])

grid = np.array([[4, 5, 6], [7, 8, 9]])

In [94]:
# vertically stack the arrays

np.vstack([x, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
# horizontally stack the arrays

y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

In [96]:
# np.dstack will stack arrays along the third axis


In [97]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])

In [98]:
x1

array([1, 2, 3])

In [99]:
x2

array([99, 99])

In [100]:
x3

array([3, 2, 1])

In [101]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [102]:
grid = np.arange(16).reshape((4, 4))

grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
upper, lower = np.vsplit(grid, [2])

print(f'upper: {upper}')
print(f'lower: {lower}')

upper: [[0 1 2 3]
 [4 5 6 7]]
lower: [[ 8  9 10 11]
 [12 13 14 15]]


In [104]:
left, right = np.hsplit(grid, [2])

print(f'left: {left}')
print(f'right: {right}')

left: [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right: [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [105]:
import numpy as np

np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [106]:
values = np.random.randint(1, 10, size= 5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [107]:
big_array = np.random.randint(1, 100, size= 1000000)

%timeit compute_reciprocals(big_array)

1.6 s ± 19.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [108]:
print(compute_reciprocals(values))
print(1.0/ values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [109]:
%timeit (1.0 / big_array)

3.78 ms ± 150 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [110]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [111]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [113]:
x = np.arange(4)
print('X =', x)
print("X + 5 =", x + 5)
print("X - 5 =", x - 5)
print('x * 2 =', x * 2)
print('X / 2 = ', x / 2)
print('X // 2 =', x // 2) #floor division

X = [0 1 2 3]
X + 5 = [5 6 7 8]
X - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
X / 2 =  [0.  0.5 1.  1.5]
X // 2 = [0 0 1 1]


In [114]:
print('-x =', -x)
print('X ** 2 =', x**2)
print('X % 2 =', x%2)

-x = [ 0 -1 -2 -3]
X ** 2 = [0 1 4 9]
X % 2 = [0 1 0 1]


In [117]:
-(0.5 * x + 1)**2

array([-1.  , -2.25, -4.  , -6.25])

In [118]:
np.add(x, 2)

array([2, 3, 4, 5])

In [121]:
x = np.array([-2, -1, 0, 1, 2])
abs(x) # converts all negative numbers to positive

array([2, 1, 0, 1, 2])

In [123]:
np.absolute(x) # does thesame thing

array([2, 1, 0, 1, 2])

In [124]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [125]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [126]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [128]:
print('theta =', theta)
print('sin(theta) =', np.sin(theta))
print('cos(theta) =', np.cos(theta))
print('tan(theta) =', np.tan(theta))

theta = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [129]:
x = [-1, 0, 1]

In [131]:
print('x =', x)
print('arcsin(x) =', np.arcsin(x))
print('arccos(x) =', np.arccos(x))
print('arctan(x) =', np.arctan(x))

x = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


In [132]:
x = [1, 2, 3]


In [133]:
print('x =', x)
print('e^x =', np.exp(x))
print('2^x =', np.exp2(x))
print('3^x =', np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [134]:
x = [1, 2, 4, 10]


In [135]:
print('x =', x)
print('ln(x) =', np.log(x))
print('log2(x) =', np.log2(x))
print('log10(x) =', np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [136]:
x = [0, 0.001, 0.01, 0.1]

In [137]:
print('exp(x) - 1 =', np.expm1(x))
print('log(1 + x) =', np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [139]:
import scipy

In [140]:
from scipy import special